name: Run Newman
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
    

jobs:
  API-with-Newman:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Newman
        run: npx newman run collection/moduit.json -e environment/environment.json --reporters htmlextra --reporter-htmlextra-export newman-report.html

      - name: Create Reports Directory
        run: mkdir -p $GITHUB_WORKSPACE/reports
      
      - name: Move Newman Report
        run: mv newman-report.html $GITHUB_WORKSPACE/reports/newman-report.html

      - name: Publish Newman Report
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: .